=== darciopacifico/omr/tags/PreSCMSetup/JazzXDoclet/src/main/resources/GeneratorConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by www.serials.ws (www.serials.ws) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="jazzGeneratorConfig">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="module">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="component">
								<xs:complexType>
									<xs:attribute name="prefix" type="xs:string" use="required"/>
									<xs:attribute name="generate" type="xs:boolean" use="optional" default="false"/>
									<xs:attribute name="override" type="xs:boolean" use="optional" default="false"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="generate" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="override" type="xs:boolean" use="optional" default="false"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="generate" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="override" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== darciopacifico/omr/tags/tag_ModalOK/JazzXDoclet/src/main/resources/ManutencaoTemplatesJazzCfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<jazzGeneratorConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="C:\darcio\java\eclipse\workspace\XdocletWizardJ2EE\GeneratorConfig.xsd">

	<module name="CentroCusto" 					generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	
	<module name="ClassificacaoAtividade" 	generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	
	<module name="Funcionario" 					generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	
	<module name="Projeto" 							generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	
	<module name="StatusHistorico" 				generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	
	<module name="TilesTemplate" 					generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	
	<module name="TipoHistorico" 					generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	
	<module name="TipoProjeto" 						generate="true" override="true">
		<component prefix="Action" 						generate="true" override="true"/>
		<component prefix="BusinessDelegate" 	generate="true" override="true"/>
		<component prefix="DAO" 						generate="true" override="true"/>
		<component prefix="Facade" 					generate="true" override="true"/>
		<component prefix="FacadeImpl" 				generate="true" override="true"/>
		<component prefix="Form" 						generate="true" override="true"/>
		<component prefix="HibernateDAO" 			generate="true" override="true"/>
		<component prefix="JDBCOracleDAO" 		generate="true" override="true"/>
		<component prefix="SessionFacade" 		generate="true" override="true"/>
		<component prefix="VLHFacade" 				generate="true" override="true"/>
		<component prefix="VLHFacadeImpl" 		generate="true" override="true"/>
		<component prefix="VLHSessionFacade" generate="true" override="true"/>
		<component prefix="VOWrapper" 				generate="true" override="true"/>
	</module>
	

</jazzGeneratorConfig>
